import Image from "next/image"
import Link from "next/link"
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = async ({children}) => {
  const response = await fetch("http://localhost:9999/userInfo", {
    cache: "no-cache"
  });
  const responses = await response.json();
  return (
    <html lang="en">
      <body>
        <Link href="/">
          <Image
          src="/img/AJOU_LOGO.png"
          width={100}
          height={100}
          alt="AjouLogo"
          />
        </Link>
        <Link href="/ultra/institution-page">아주Bb 안내사항</Link>
        <Link href="/ultra/profile">.{responses.name}</Link>
        <Link href="/ultra/stream">활동 스트림</Link>
        <Link href="/ultra/course">코스</Link>
        <Link href="/ultra/organization">조직</Link>
        <Link href="/ultra/calendar">캘린더</Link>
        <Link href="/ultra/messages">메시지</Link>
        <Link href="/ultra/grades">성적</Link>
        <Link href="/ultra/tools">도구</Link>
        {children}
      </body>
    </html>
  )
}
export default RootLayout;