import Image from "next/image"
import Link from "next/link"
import SideBar from './sideBar';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = async ({children}) => {
  const response = await fetch("http://localhost:9999/userInfo", {
    cache: "no-cache"
  });
  const responses = await response.json();
  return (
    <html lang="en">
      <body>
        <>
          <SideBar
            name={responses.name} />
        </>
        {children}
      </body>
    </html>
  )
}
export default RootLayout;