'use client';
import Image from "next/image"
import React from 'react'
import Link from "next/link"
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const sideBar = (props) => {
    return (
    <>
        <div className = 'sideBarConfig'>
            <Link href="/">
                <Image
                src="/img/AJOU_LOGO.png"
                width={100}
                height={100}
                alt="AjouLogo"
                />
            </Link>
            <Link href="/ultra/institution-page">
                <span>아주Bb 안내사항</span>
            </Link>
            <Link href="/ultra/profile">
                <span>.{props.name}</span>
            </Link>
            <Link href="/ultra/stream">
                <span>활동 스트림</span>
            </Link>
            <Link href="/ultra/course">
                <span>코스</span>
            </Link>
            <Link href="/ultra/organization">
                <span>조직</span>
            </Link>
            <Link href="/ultra/calendar">
                <span>캘린더</span>
            </Link>
            <Link href="/ultra/messages">
                <span>메시지</span>
            </Link>
            <Link href="/ultra/grades">
                <span>성적</span>
            </Link>
            <Link href="/ultra/tools">
                <span>도구</span>
            </Link>
        </div>

            <style jsx>{`
            .sideBarConfig{
                flex-direction: column;
            }
            `}</style>    
    </>
    
  )
}
export default sideBar;
